Components
raheebwa/mv-react-bookstore pull request #2
Opened 2020-06-03 22:21 UTC by damiecode

Thank you for reviewing our work.
- [x] Prepare the directory structure 
- [x] Implement the App component 
- [x] Implement the BooksList component
- [x] Implement the Book component
- [x] Implement the BooksForm component
- [x] Define the Redux actions and reducers
- [x] Initialize the Redux store

2020-06-05 09:12 UTC, shloch requested changes
## Hello @damiecode , @raheebwa 

All your Logic stands out properly....but please for conformity with guidelines of this project, you have 03 files to relocate to specific folders before you get a thumbs up

waiting for a last re-review

### Happy coding

2020-06-05 09:12 UTC, shloch commented on src/App.js
> +export default App;
Please relocate this this file to `"src/components/"` folder. Has nothing to do with performance or workings of  the project, but this is how the guideline wants it structured. Hope you understand, thanks

2020-06-05 09:12 UTC, shloch commented on src/components/BooksForm.js
> +
Relocate this component inside `"src/containers/"` folder ....... all containers, will be in this folder, thanks

2020-06-05 09:12 UTC, shloch commented on src/components/BooksList.js
> +
Relocate this file into `"src/containers"` folder

2020-06-06 16:39 UTC, bellom approved these changes
## Hi Team :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-06-08 14:12 UTC, merged